import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/Header";
import SessionProvider from "../components/auth/SessionProvider";
import { DataProvider } from "../contexts/DataContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SessionProvider>
          <DataProvider>
            <Header />
            {children}
          </DataProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
