import type { Metadata } from "next";
import Header from "../components/layout/Header";
import { ConversationProvider } from "../contexts/ConversationContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ConversationProvider>
          <Header />
          {children}
        </ConversationProvider>
      </body>
    </html>
  );
}
